services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile

    command: [ "sh", "-c", "while sleep 1000; do :; done" ]

    privileged: true

    volumes:
      - type: bind
        source: ..
        target: /workspace
      - type: volume
        source: registry
        target: /var/lib/registry

  registry:
    image: ghcr.io/project-zot/zot:v2.1.0

    volumes:
      - type: bind
        source: ./zot.json
        target: /etc/zot/config.yml
        read_only: true
      - type: volume
        source: registry
        target: /var/lib/registry

volumes:
  registry:
