name: Built and Test
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    services:
      registry:
        image: ghcr.io/project-zot/zot-minimal:v2.1.0
        ports:
          - 5000:5000

    strategy:
      matrix:
        node: [20, 22]
    steps:
      - name: Wait registry
        run: >
          for ((i=1; i<=30; i++)); do
              status_code=$(curl -o /dev/null -s -w "%{http_code}\n" "http://registry:5000/v2/")
              if [ "$status_code" -eq 200 ]; then
                  exit 0
              fi

              sleep 1
          done
          exit 1

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - run: npm clean-install
      - run: npx biome ci .
      - run: npm test
      - run: npm run build
